agents/urls.py
from django.urls import path 
from .views import (
    AgentListView, AgentCreateView, AgentUpdateView, AgentDeleteView, AgentDetailView
    )

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name = 'agent-list'),
    path('create/', AgentCreateView.as_view(), name = 'agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name = 'agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name = 'agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name= 'agent-delete'),
]

crm_django/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import LandingPageView, SignupView
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('', LandingPageView.as_view(), name= "landing-page"),
    path('login/', LoginView.as_view(), name ="login"),
    path('logout/', LogoutView.as_view(), name ="logout"),
    path('signup/', SignupView.as_view(), name ="signup"),
    path('reset-password/', PasswordResetView.as_view(), name ="reset-password"),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name ="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name ="password_reset_confirm"),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name ="password_reset_complete"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leads/urls.py
from django.urls import path 
from .views import lead_list, lead_detail, lead_create, lead_update, lead_delete, LeadListView, LeadDetailView, LeadUpdateView, LeadDeleteView, LeadCreateView, AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView,LeadCategoryAdd,LeadCategoryDelete,CategoryUpdateView

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name = 'lead-list'),
    #We specify the typy of the PK that is expected so we don't get errors when
    #we write other String types URLS
    path('<int:pk>/', LeadDetailView.as_view(), name = 'lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name = 'lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name = 'lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name = 'assign-agent'),
    path('<int:pk>/category', LeadCategoryUpdateView.as_view(), name = "lead-category-update"),
    path('create/', LeadCreateView.as_view(), name = 'lead-create'),
    path('categories/', CategoryListView.as_view(), name ="category-list"),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name ="category-detail"),
    path('categories/<int:pk>/delete',LeadCategoryDelete.as_view(), name= "category-delete" ),
    path('categories/<int:pk>/update',CategoryUpdateView.as_view(), name= "category-update" ),
    path('categories/add',LeadCategoryAdd.as_view(), name= "category-add" ),

]

templates/agent-create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<header class="text-gray-600 body-font">
    <div class="mt-5 mb-5 max-w-lg mx-auto">
      <a href = "{% url 'agents:agent-list' %}" class="text-white inline-flex items-center bg-gray-500 border-0 py-1 px-3 focus:outline-none hover:bg-blue-400 rounded text-base mt-4 md:mt-0">Back
      </a>
    </div>
    
</header>
<div class= "max-w-lg mx-auto">
    <div>
      <h1 class = "text-4xl text-gray-800 ">Create a new Agent</h1>
    </div>
      <form class = "mt-10"method ="post">
          {% csrf_token %}
          {{form|crispy}}
          <button class = "mt-1 text-white w-full bg-gray-500 hover:bg-blue-400 px-3 py-2 rounded-md mb-10 "type = "submit">Create</button>
      </form>
  </div>
{% endblock content %}

templates/agent-detail.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM</title>
    <link href="{%static 'css/styles.css'%}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class= "mt-10 max-w-5xl mx-auto">
      <div class="mb-6 text-blue-400">
        <a href="{% url 'agents:agent-list' %}" class = "text-red-400 hover:text-gray-600 ">Back to Agents</p>
      </div>
       <section class="text-gray-600 body-font overflow-hidden">
          <div class=" max-w-7xl  mx-auto">
            <div class="w-full mx-auto">
              <div class=" w-full mb-6 lg:mb-0">
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.first_name}} {{agent.user.last_name}}</h1>
                <div class="flex mb-4">
                  <a  href ="{% url 'agents:agent-detail' agent.pk%}"class="flex-grow text-blue-400 border-b-2 border-blue-400 py-2 text-lg px-1">Description</a>
                  <a  href ="{% url 'agents:agent-update' agent.pk%}"class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Edit</a>
                </div>
                <div class="flex py-2">
                  <span class="text-gray-500">UserName</span>
                  <span class="ml-auto text-gray-900">{{agent.user.username}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                  <span class="text-gray-500">Email</span>
                  <span class="ml-auto text-gray-900">{{agent.user.email}}</span>
                </div>
                 <div class="flex border-t border-gray-200 py-2">
                  <span class="text-gray-500">Phone Number</span>
                  <span class="ml-auto text-gray-900">{{agent.user.phone_number}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                  <span class="text-gray-500">Age</span>
                  <span class="ml-auto text-gray-900">{{agent.user.age}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                  <span class="text-gray-500">Added Date</span>
                  <span class="ml-auto text-gray-900">{{agent.user.date_added}}</span>
                </div>
                </div>
              </div>
            </div>
          </div>
</section>
    </div>
</body>
</html>

templates/assign-agent.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<header class="text-gray-600 body-font">
    <div class="mt-5 mb-5 max-w-lg mx-auto">
      <a href = "{% url 'leads:lead-list' %}" class="text-white inline-flex items-center bg-gray-500 border-0 py-1 px-3 focus:outline-none hover:bg-blue-400 rounded text-base mt-4 md:mt-0">Back
      </a>
    </div>
    
</header>
<div class= "max-w-lg mx-auto">
    <form method ="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type = "submit" class = "mt-2 text-white w-full bg-gray-500 hover:bg-blue-400 px-3 py-2 rounded-md">Assign</button>
    </form>
</div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM</title>
    <link href="{%static 'css/styles.css'%}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class= "max-w-7xl mx-auto">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/category-delete.html
{% load static %}
{% load tailwind_filters %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM</title>
    <link href="{%static 'css/styles.css'%}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class= "mt-10 max-w-7xl mx-auto">
       <div class= "max-w-lg mx-auto mb-20">
          <div class="mb-6 text-blue-400">
            <a href="{% url 'leads:category-list' %}" class = "text-blue-400 hover:text-gray-600 ">Back to Categories</p>
          </div>
          <div>
            <h1 class = "text-2xl text-gray-800 ">Are you sure you want to delete this Category?</h1>
          </div>
            <form class = "mt-10"method ="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class = "mt-1 text-white w-full bg-gray-500 hover:bg-red-400 px-3 py-2 rounded-md"type = "submit">Delete</button>
            </form>
        </div>
    </div>
</body>
</html>

templates/category-update.html
{% load static %}
{% load tailwind_filters %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM</title>
    <link href="{%static 'css/styles.css'%}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class= " mt-10 max-w-5xl mx-auto">
      
        <header class="text-gray-600 body-font">
            <div class="mt-5 mb-5 max-w-lg">
            <a href = "{% url 'leads:category-list' %}" class="text-white inline-flex items-center bg-gray-500 border-0 py-1 px-3 focus:outline-none hover:bg-blue-400 rounded text-base mt-4 md:mt-0">Back
            </a>
            </div>
            
        </header>
       <section class="text-gray-600 body-font overflow-hidden">
          <div class=" max-w-7xl  mx-auto">
            <div class="w-full mx-auto">
              <div class=" w-full mb-6 lg:mb-0">
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{category.name}}</h1>
                 <form method ="post">
                  {% csrf_token %}
                  {{form|crispy}}
                  <button class = " mt-1 mb-20 text-white w-full bg-gray-500 hover:bg-blue-400 px-3 py-2 rounded-md" type = "submit">Update</button>
                </form>
                </div>
              </div>
            </div>
          </div>
</section>
    </div>
</body>
</html>

templates/landing-page.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-5 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="landing-page" src="../media/images/landing-page-1.png"/>
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">CRM to manage your Leads</h1>
      <p class="mb-8 leading-relaxed">The way to a simpler life</p>
      <div class="flex justify-center">
        <a href ={% url 'login' %} class="inline-flex text-white bg-gray-500 hover:bg-blue-400 border-0 py-2 px-6 focus:outline-none rounded text-lg">Login</a>
              <a href={% url 'signup' %} class="ml-4 inline-flex text-white bg-gray-500 hover:bg-blue-400 border-0 py-2 px-6 focus:outline-none rounded text-lg">Signup</a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/lead-category-update.html
{% load static %}
{% load tailwind_filters %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM</title>
    <link href="{%static 'css/styles.css'%}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class= "mt-10 max-w-5xl mx-auto">
      <div class="mb-6 text-blue-400">
        <a href="{% url 'leads:lead-list' %}" class = "text-red-400 hover:text-gray-600 ">Back to Leads</p>
      </div>
       <section class="text-gray-600 body-font overflow-hidden">
          <div class=" max-w-7xl  mx-auto">
            <div class="w-full mx-auto">
              <div class=" w-full mb-6 lg:mb-0">
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
                <div class="flex mb-4">
                  <a  href ="{% url 'leads:lead-detail' lead.pk%}"class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
                  <a href = "{% url 'leads:lead-category-update' lead.pk%}"class="flex-grow text-blue-400 border-b-2 border-blue-400 py-2 text-lg px-1">Category</a>
                  {% if request.user.is_organizer %}
                  <a  href ="{% url 'leads:lead-update' lead.pk%}"class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Edit</a>
                  {% endif %}
                </div>
                 <form method ="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class = "mt-1 text-white w-full bg-gray-500 hover:bg-blue-400 px-3 py-2 rounded-md" type = "submit">Assign</button>
            </form>
                </div>
              </div>
            </div>
          </div>
</section>
    </div>
</body>
</html>

templates/lead-create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<header class="text-gray-600 body-font">
    <div class="mt-5 mb-5 max-w-lg mx-auto">
      <a href = "{% url 'leads:lead-list' %}" class="text-white inline-flex items-center bg-gray-500 border-0 py-1 px-3 focus:outline-none hover:bg-blue-400 rounded text-base mt-4 md:mt-0">Back
      </a>
    </div>
    
</header>
<div class= "max-w-lg mx-auto">
    <div>
      <h1 class = "text-4xl text-gray-800 ">Create a new Lead</h1>
    </div>
      <form class = "mt-10"method ="post">
          {% csrf_token %}
          {{form|crispy}}
          <button class = "mt-1 text-white w-full bg-gray-500 hover:bg-blue-400 px-3 py-2 rounded-md mb-20"type = "submit">Create</button>
      </form>
  </div>
{% endblock content %}

templates/lead-delete.html
{% load static %}
{% load tailwind_filters %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM</title>
    <link href="{%static 'css/styles.css'%}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class= "mt-10 max-w-7xl mx-auto">
       <div class= "max-w-lg mx-auto mb-20">
          <div class="mb-6 text-blue-400">
            <a href="{% url 'leads:lead-list' %}" class = "text-blue-400 hover:text-gray-600 ">Back to Leads</p>
          </div>
          <div>
            <h1 class = "text-2xl text-gray-800 ">Are you sure you want to delete this Lead?</h1>
          </div>
            <form class = "mt-10"method ="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class = "mt-1 text-white w-full bg-gray-500 hover:bg-red-400 px-3 py-2 rounded-md"type = "submit">Delete</button>
            </form>
        </div>
    </div>
</body>
</html>

templates/lead-update.html
{% load static %}
{% load tailwind_filters %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CRM</title>
    <link href="{%static 'css/styles.css'%}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class= " mt-10 max-w-5xl mx-auto">
      <div class="mb-6 text-blue-400">
        <a href="{% url 'leads:lead-list' %}" class = "text-red-400 hover:text-gray-600 ">Back to Leads</p>
      </div>
       <section class="text-gray-600 body-font overflow-hidden">
          <div class=" max-w-7xl  mx-auto">
            <div class="w-full mx-auto">
              <div class=" w-full mb-6 lg:mb-0">
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
                <div class="flex mb-4">
                  <a  href ="{% url 'leads:lead-detail' lead.pk%}"class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
                  <a href = "{% url 'leads:lead-category-update' lead.pk%}"class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
                  <a  href ="{% url 'leads:lead-update' lead.pk%}"class="flex-grow text-blue-400 border-b-2 border-blue-400 py-2 text-lg px-1">Edit</a>
                </div>
                 <form method ="post">
                  {% csrf_token %}
                  {{form|crispy}}
                  <button class = " mt-1 mb-20 text-white w-full bg-gray-500 hover:bg-blue-400 px-3 py-2 rounded-md" type = "submit">Update</button>
                </form>
                </div>
              </div>
            </div>
          </div>
</section>
    </div>
</body>
</html>

templates/leadCategory-hotLead.html
{% extends 'base.html' %}

{% block content %}
<header class="text-gray-600 body-font">
    <div class="mt-5 mb-5 max-w-lg mx-auto">
      <a href = "{% url 'leads:category-list' %}" class="text-white inline-flex items-center bg-gray-500 border-0 py-1 px-3 focus:outline-none hover:bg-blue-400 rounded text-base mt-4 md:mt-0">Back
      </a>
    </div>
</header>
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-5 items-center justify-center flex-col">
    <div class="text-center w-full">
      <h1 class="title-font sm:text-4xl text-5xl mb-4 font-medium text-gray-900">Hot Lead</h1>
        <p class="mb-8 leading-relaxed">This type of qualified lead meets all the required criteria which most of the time is set. So how to know if it’s a hot lead? Simple. Apply the BANT lead qualifying system.
            B is for Budget: The prospect has set or prepared a budget and is just ready for disposal at anytime a project proposal is approved by the management.  
            A for Authority: The contact person you speak to could either be the Person In charge, or the Recommender. He should have the final word to either say “yes” or “no” to the proposal.
            N is for Need: Need would always top the set of qualifying questions in a telemarketing script. When a need from the prospect is identified, this sends a signal of a brewing lead.
            T is for Time frame: The point period from the time you spoke with the prospect to the planned or projected period of purchase or implementation of the new product or service.
        </p>
      <div class="flex justify-center">
        <div class=" -m-4 w-full">
    <div class="overflow-x-auto ">
        <div class="w-full flex font-sans">
            <div class="w-full">
                <div class="bg-white shadow-md rounded my-6">
                    <table class="min-w-max w-full table-auto">
                        <thead>
                            <tr class="bg-gray-800 text-white uppercase text-sm leading-normal">
                                <th class="py-3 px-6 text-left">Lead</th>
                                <th class="py-3 px-6 text-left">Phone</th>
                                <th class="py-3 px-6 text-center">Email</th>
                                <th class="py-3 px-6 text-center">Contacted</th>
                                <th class="py-3 px-6 text-center">Category</th>
                                {% if request.user.is_organizer %}
                                <th class="py-3 px-6 text-center">Edit</th>
                                {% else %}
                                <th class="py-3 px-6 text-center">View</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody class="text-gray-600 text-sm font-light">
                        {% for lead in leads %}
                            <tr class="border-b border-gray-200 hover:bg-gray-300">
                                <td class="py-3 px-6 text-left whitespace-nowrap">
                                    <div class="flex items-center">
                                        <span class="font-medium text-black">{{lead.first_name}} {{lead.last_name}}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-left">
                                    <div class="text-black items-center">
                                        <span>{{lead.phone_number}}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    <div class=" text-black items-center justify-center">
                                        <span>{{lead.email}}</span>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    {% if lead.contacted %}
                                    <a href ="{% url 'leads:lead-category-update' lead.pk%}" class ="text-black py-1 px-3 rounded-full bg-yellow-400 hover:bg-blue-400 ml-10">
                                        Contacted
                                    </a>
                                    {% else %}
                                    <a href ="{% url 'leads:lead-category-update' lead.pk%}" class ="text-black py-1 px-3 rounded-full bg-red-800 text-white hover:bg-green-400 ml-10">
                                        Not Contacted
                                    </a>
                                    {% endif %}
                                </td>
                                  <td class="py-3 px-6 text-center whitespace-nowrap">
                                    <div class=" items-center">
                                    <a href ="{% url 'leads:lead-category-update' lead.pk%}" class ="ml-10">
                                        <span class="hover:text-blue-400 font-medium">{{lead.category}}</span>
                                    </a>
                                    </div>
                                </td>
                                <td class="py-3 px-6 text-center">
                                    <div class="flex item-center justify-center">
                                        <div class="w-4 mr-2 transform hover:text-blue-400 hover:scale-110">
                                        <a href  = "{% url 'leads:lead-detail' lead.pk %}">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                                            </svg>
                                        </a>
                                        </div>
                                        {% if request.user.is_organizer %}
                                        <div class="w-4 mr-2 transform hover:text-yellow-400 hover:scale-110">
                                        <a href  = "{% url 'leads:lead-update' lead.pk %}">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                            </svg>
                                        </a>
                                        </div>
                                        <div class="w-4 mr-2 transform hover:text-red-500 hover:scale-110">
                                        <a href  = "{% url 'leads:lead-delete' lead.pk %}">
                                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </a>
                                        </div>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/scripts.html
{% load static %}

<scripts src = "{%static 'js/main.js'%}"></scripts>